list_en =["https://apnews.com/",
        "https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en",
        "https://www.nationthailand.com/",
        "https://www.nbcnews.com/",
        "https://www.nytimes.com/",
        "https://www.nbcnews.com/",
        "https://www.cbsnews.com/",
        "https://www.usatoday.com/",
        "https://www.foxnews.com/",
        # "https://www.dailymail.co.uk/home/index.html/"
        "https://www.businessinsider.com/",
        "https://elitedaily.com/",
        "https://www.cnet.com/",
        "https://www.cnbc.com/world/?region=world/",
        "https://www.marketwatch.com/",
        "https://www.bangkokpost.com/",
        "https://www.npr.org/",
        # "https://www.nydailynews.com/",
        "https://nypost.com/",
        "https://time.com/",
        "https://mashable.com/",
        "https://www.sfgate.com/",
        "https://www.theblaze.com/",
        "https://www.telegraph.co.uk/",
        "https://www.vice.com/en/section/world/",
        "https://www.chron.com/",
        "https://www.vox.com/",
        "https://www.chicagotribune.com/",
        "https://www.thedailybeast.com/",
        "https://www.salon.com/",
        "https://mic.com/",
        "https://www.nj.com/",
        "https://www.freep.com/",
        "https://www.theatlantic.com/",
        "https://www.mlive.com/",
        "https://www.engadget.com/",
        "https://techcrunch.com/",
        "https://www.boston.com/",
        "https://www.al.com/",
        ]
list_th = ["https://www.thairath.co.th/news",
          "https://www.komchadluek.net/",
          "https://www.chiangmainews.co.th/",
          "https://www.matichon.co.th/",
          "https://www.dailynews.co.th/",
          "https://www.bangkokbiznews.com/",
          "https://www.thansettakij.com/",
          "https://www.siamturakij.com/home",
          "https://www.bangkokpost.com/",
          "https://www.thaipost.net/",
          "https://www.nationthailand.com/",
          "https://www.siamsport.co.th/home",
          "https://www.tv5.co.th/tv5hd1-web/page-onair.php",
          "https://news.ch7.com/",
          "https://tna.mcot.net/",
          "https://www.msn.com/th-th/news/",
          "https://www.ryt9.com/",
          "https://www.prachachat.net/finance",
          "https://www.posttoday.com/",
          ]


